version: "3"
services:
  mymongo:
    image: "mongo"

  mynode:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
